### ISSUE TITLE
Timeout options

### ISSUE THREAD

**Issue by anotherdevs** [nsqio/nsq#1028]
Hi

Can someone please help help my explain what these timeout represent:

max-msg-timeout
Description: maximum duration before a message will timeout (default 15m0s)
What state is the message in before it can timeout? What happens when they timeout?

max-req-timeout
Description: maximum requeuing timeout for a message (default 1h0m0s)
After this hour is the message deleted?

msg-timeout
Description: duration to wait before auto-requeing a message (default "1m0s")
Is the message already queued or is it when a message has been reserved?

Something that isn't documented: how to disable timeouts?

I need to make sure that a message never gets deleted.

**Comment by ploxiln** [comment]
The timeouts can be changed, by the consumer, when it connects to nsqd, but only up to the maximums.

In the most typical case, a 1 minute timeout applies: if nsqd sends a message to a consumer, and does not hear back about that message (neither REQUEUE nor FINISH nor TOUCH), then after a minute nsqd automatically "re-queues" the message, so it can be delivered again, possibly to a different consumer.

It sounds like what you want is "infinite retries". nsqd includes the number of "attempts" along with a message it delivers to a consumer, so the consumer knows how many times the message was already timed-out or proactively re-queued, instead of "finished". The "retry limit" is (somewhat surprisingly) implemented on the consumer side, and the default is usually 5 - on the 5th retry, the consumer will immediately "finish" the message instead of trying to process it at all. That's the default, and can be easily changed in the consumer.

**Comment by anotherdevs** [comment]
Hi @ploxiln 

Thank you for the reply.

I want to make sure that if a subscriber (consumer) is disconnected for, lets say 24 hours, that no messages are deleted from NSQ.

Are you able to explain more detailed what the aforementioned variables actually does?

Fx. (and I only guess here):

max-msg-timeout: If a message has been sitting in waiting for more than 15 minutes it will get deleted and no subscriber can retrieve the message from the server.

I am not sure if that is the case - if so, I want to disable this feature.

**Comment by anotherdevs** [comment]
Hi @ploxiln 

Thank you again for your reply.

Why and when should i change these values (fx. what will i accomplish setting them higher or lower):

max-msg-timeout
max-req-timeout
msg-timeout

You mentioned maximum values, however I cannot find the maximum values in the documentation. Can you help me describe these maximums?

**Comment by ploxiln** [comment]
Messages will wait in the queue to be delivered indefinitely, with no timeout. msg-timeout is the default message-processing timeout. The consumer can set a different message timeout when it connects, and it can also do a TOUCH to re-set the timeout and give itself more time for a message, but nsqd will not wait any longer than max-msg-timeout.

The consumer can requeue a message before the timeout, and it can specify a "delay", so nsqd will not re-send the message until after the delay. But nsqd will never delay more than max-req-timeout before making the message available to consume again.

**Comment by wxiaoguang** [comment]
This is pretty useful, should these information be written into the help document?
