### ISSUE TITLE
question: why defered msg store in c.deferredMessages, but not in topic?

### ISSUE THREAD

**Issue by kulv2012** [nsqio/nsq#1037]
hi , I was wondering why defered message are stored in each channel, but not in Topic ? 
as there will be many channel in one topic , 
if put deferredPQ in the topic , it sound will be more efficient ?

**Comment by ploxiln** [comment]
The deferred queue is also for re-queued nsq messages, which should only be re-delivered on the channel which they timed-out or were re-queued on. We could theoretically have a separate deferred queue on the topic for defer-published messages. But I think it is considered not worth it, since we still need a deferred queue for each channel (for re-queued messages), and we still need to copy the message for each channel even if it is not deferred.

**Comment by kulv2012** [comment]
got it , thanks, With one deferredPQ  is more simple , maybe worth it .
