### ISSUE TITLE
nsq_to_http

### ISSUE THREAD

**Issue by lescudero74** [nsqio/nsq#1095]
hola buen dia,
yo tengo 4 tópicos, la duda es como configurar el nsq_to_http para cada uno de ellos, porque cuando tiro el comando, me desactiva uno y comienza a andar el otro, no se como configurar para que anden en simultaneo. desde ya muchas gracias
saludos!!

**Comment by lyle-nel** [comment]
I though I would translate this question to english. Its very crude, but it might assist people that want to understand your question.

Hi good day,
I have 4 topics, the question is how to configure the nsq_to_http for each one of them, because when I throw the command, I deactivate one and start walking the other, I do not know how to configure them to run simultaneously. Thank you very much
regards!!

**Comment by mreiferson** [comment]
These kinds of questions are best left to the [mailing list](https://groups.google.com/d/forum/nsq-users). We would need more information about what commands you're running and how the individual components are configured to help.
