### ISSUE TITLE
docs: Where's the doc for message statechart diagram?

### ISSUE THREAD

**Issue by jueljust** [nsqio/nsq#1096]
How many ways to reach re-queued and timeout state?
i really need the statechart to check why i got i got a lot of re-queue and time out

**Comment by ploxiln** [comment]
Backoff and rate-control can be complicated, but message state is simple.

There is one way for a message to timeout - it is delivered to a consumer, and the consumer does not "finish" the message before the timeout. (The timeout can be configured in a couple different ways. The default is 60 seconds. There is also TOUCH but that is sort of another way of changing the timeout for a single message.)

A timed-out message is always re-queued. A consumer can also explicitly re-queue a message instead of finishing it (and it can specify for how long it should be deferred before it can be delivered again).

Client libraries have a "max attempts" option/setting (a common default is 5), and if a consumer receives a message which has already had this number of attempts, the client library will "finish" it without handing it to your handler function.
