### ISSUE TITLE
message do not in-flight but the client connected .

### ISSUE THREAD

**Issue by RifeWang** [nsqio/nsq#1146]
sometimes, I found that the client conntected to nsqd, but the message store in depth and do not in-flight, so I have to  restart my client and then it looks works fine. 
what occurred to this and how to solve it ?

**Comment by ploxiln** [comment]
If the client fails to process a message, for example if there is some kind of exception or error, it will back-off exponentially, pausing for just a second or two at first, then longer and longer. When you restart it, it forgets how long it was backing-off due to errors. It is also possible for you to "requeue without backoff".

It is also possible that you need to set a higher max-in-flight for the client. If the number of nsqd which have a topic is greater than the client's max-in-flight, it will send a "ready count" of 1 to as many nsqd as possible, and 0 to the rest, and periodically redistribute its "ready count" so that eventually it should get messages from all nsqd.

If you still have problems, you should report stats from nsqd, nsq client library or utility, versions, etc. If possible you should ask on the mailing list linked from the README.

**Comment by RifeWang** [comment]
thanks for your answer , I will check my client code again.
