### ISSUE TITLE
empty

### ISSUE THREAD

**Issue by cossbow** [nsqio/nsq#1155]
Empty topic operate will move message to channel, empty channel operate  will delete all message.
How do i only delete consumed messages, not effect the unconsumed. 
I want to release disk space when queue was too long.

**Comment by mdh67899** [comment]
it looks like you should delete the invalid backend queue file manually

You should check the metadata of the backend file and delete all the files before the read serial number according to the serial number of the read file of the metadata.

In topic level: 
topic backend metadata file: `{DataPath/topicName}.diskqueue.meta.dat`
topic backend data file: `{DataPath/topicName}.diskqueue.{fileNum}.dat`

In channel level:
channel backend metadata file: `{DataPath/{topicName:channelName}}.diskqueue.meta.dat`
channel backend data file: `{DataPath/{topicName:channelName}}.diskqueue.dat`

metadata file content format:
```
fmt.Fscanf(f, "%d\n%d,%d\n%d,%d\n",
	&depth,
	&d.readFileNum, &d.readPos,
	&d.writeFileNum, &d.writePos)
```

**for example:**
if the topic name is `order`, the default topic backend metadata file path should be: `order.diskqueue.meta.dat`, and content is:
```
1000
8,100
9:300
```
the valid data file is `order.diskqueue.000008.dat`、`order.diskqueue.000009.dat`, you can delete the file:  `order.diskqueue.00000[0-7].dat`

**Comment by ploxiln** [comment]
> Empty topic operate will move message to channel

Not really - just like for channel, "empty topic" deletes all messages queued on the topic. But messages normally only queue on the topic if there are no channels, or if the topic is paused, otherwise they drain from the topic as they are copied to all channels.

> How do i only delete consumed messages, not effect the unconsumed.

This is what is supposed to happen by default, but it is limited by the disk segment size (a whole diskqueue segment file must be finished before it can be deleted). This is controlled by the nsqd `--max-bytes-per-file` option which defaults to 100 MiB - you may want to reduce this, perhaps to 10 MiB or so.
