### ISSUE TITLE
nsqd: memory leak in nsqd/GC or what?

### ISSUE THREAD

**Issue by mateusz-szczyrzyca** [nsqio/nsq#1156]
Hi folks,

I've observed strange behaviour.

I was testing nsq daemon (v1.1.1 built on go1.12) and I've sent 1 000 000 messages each time to 3 different channels. 
nsd daemon was started with `--log-level=debug` and `--mem-queue-size=1000000` options. 

Later I was consuming all of these messages channel by channel, not at the same time. 

For producing/consuming messages I use `github.com/nsqio/go-nsq` package

When I started this process (at that time all channels had messages 1M or more, some of them were written to the disc of course due to `--mem-queue-size=1000000`) RSS memory usage was around `680MB`. 
When all messages from all channels (and thus from entire topic) were already consumed, RSS strangely rocketed to around `752MB`. Then, of course, I emptied queue, later deleted channel, and finally I deleted the entire topic as well from nsqadmin UI.

Currently I have no topic, no channels and still, memory usage is around `752MB`. The nsqd is still running for more than 30 minutes since I removed the consumed topic from the UI. 

Meantime I also send some messages (up to 50k) and consumed all of them but this activity only has increased the memory usage.

This is what I got from `/stats`:
```
nsqd v1.1.1-alpha (built w/go1.12)
start_time 2019-04-16T21:11:39+02:00
uptime 36m36.563234487s

Health: OK

Memory:
   heap_objects             	2108
   heap_idle_bytes          	736518144
   heap_in_use_bytes        	1089536
   heap_released_bytes      	736485376
   gc_pause_usec_100        	425
   gc_pause_usec_99         	425
   gc_pause_usec_95         	120
   next_gc_bytes            	4194304
   gc_total_runs            	36

Topics: None

Producers: None
```

And this is my question: is this intended  behaviour? Or maybe this is some kind of memory leak in `nsqd`? Or maybe this is GC problem in Go 1.12?

**Comment by mateusz-szczyrzyca** [comment]
Of course restart `nsqd` fully reclaims this memory to the system. 

What also can be interesting - when all messages were consumed, queue emptied, channel and topic removed `nsqd` had CPU usage between `15-30%` - basically doing nothing (debug log level didn't show anything special except heartbeats), no producer/consumer was connected then.

**Comment by mreiferson** [comment]
Hi @mateusz-szczyrzyca, thanks for your question.

In terms of memory footprint, I think what you're observing is the (normal) behavior of Go's GC/runtime rather than anything specific to `nsqd`.

By default, Go will perform a GC when the heap size doubles, and it calculates that target during the mark phase. This value can be tuned via the `GOGC` environment variable:

> The GOGC variable sets the initial garbage collection target percentage. A collection is triggered when the ratio of freshly allocated data to live data remaining after the previous collection reaches this percentage. The default is GOGC=100. Setting GOGC=off disables the garbage collector entirely

However this only explains _when_ a GC runs, not what is being reported as RSS. This is where it gets a little more complicated. You can see in the memory stats returned that Go has "released" almost all of the bytes allocated, indicating that it has indeed performed a GC and "freed" memory (there is no leak). Given that this is virtual address space, Go "releases" them only in the sense that it is _advising_ the OS that they can be reclaimed, so it won't necessarily be reflected in RSS. If the host were actually under memory pressure, I'm pretty sure things would work as expected and the memory would indeed be reclaimed. Here's a more detailed summary of what's going on:

https://utcc.utoronto.ca/~cks/space/blog/programming/GoNoMemoryFreeing

**Comment by mreiferson** [comment]
> What also can be interesting - when all messages were consumed, queue emptied, channel and topic removed nsqd had CPU usage between 15-30% - basically doing nothing (debug log level didn't show anything special except heartbeats), no producer/consumer was connected then.

Forgot to respond to this, sorry. This isn't expected behavior, if you could provide some sort of reproducible test case this is something we'd like to better understand. Thanks.

**Comment by mateusz-szczyrzyca** [comment]
@mreiferson: thanks for this useful link with the explanation.

Regarding CPU usage - I will try to reproduce it and if the problem persists then I will open a new issue.
