### ISSUE TITLE
Learn from get topic

### ISSUE THREAD

**Issue by lvchengchang** [nsqio/nsq#1165]
In apps/nsqd/nsqd.go # line 460
```go
n.RLock()
	t, ok := n.topicMap[topicName]
	n.RUnlock()
	if ok {
		return t
	}

	n.Lock()

	t, ok = n.topicMap[topicName]
	if ok {
		n.Unlock()
		return t
	}
```
i want learn why you lock topic map too many.,i found DeleteExistingTopic use lock this map third! i'm question . why not use once lock try apply topicMap[name] again.

this is my question.if you busy can shutdown this issues.

**Comment by jehiah** [comment]
This update pattern is optimized for hot reads and infrequent writes. This pattern allows concurrent reads while infrequently getting an exclusive write lock.

It uses a READ lock to check topicMap (hot path) and then acquires a WRITE lock to add an entry in topicMap. Because it has released the READ lock to acquire a WRITE lock it must re-check presence after acquiring a WRITE lock.
