### ISSUE TITLE
Question: is there a way to have a topic dropping messages without channels

### ISSUE THREAD

**Issue by bandesz** [nsqio/nsq#1191]
Our use case is that we have a secondary NSQ cluster where we create topics using an internal topic name in the messages from the first cluster. This way we can consume all messages from the first cluster or only specific ones from the second one. (We have thousands of topics)

As not all topics are consumed in the second cluster we have a simple app which creates a channel for all topics and drains these channels (and therefore the topics).

Is there a way to create a topic that simply drops the messages if there are no channels for that topic?

**Comment by ploxiln** [comment]
there are "ephemeral" topics - those whose name ends in `#ephemeral`

**Comment by bandesz** [comment]
In my described scenario a topic should behave the following way:
- if there are no channels all messages should be dropped
- if there are channels then no messages should be lost and topic messages should be saved to disk if NSQ is unable to copy the messages quick enough to the channels

I don't think ephemeral channels are suitable for this, or am I wrong?

**Comment by ploxiln** [comment]
Ephemeral topics and ephemeral channels are separate things. You are correct that ephemeral topics do not save messages to the disk-queue if the mem-queue overflows because messages cannot be copied to channels fast enough. However, in practice, this never happens. You will probably see that topics never build up even 10 messages in the mem-queue while channels exist, so with the default mem-queue size of 10,000 it will never happen.

It's not a bad idea, though, to use normal topics and ephemeral channels, and have a "simple app" drain all relevant topics. For this you may find `nsq_to_file` or `nsq_tail` appropriate (you may want to have a back-up of just the last couple days worth of messages anyway). This really may work better than the alternatives.

However, it may be inefficient to have thousands of topics. NSQ was designed for many messages (thousands per second, spread over multiple servers) sent over fewer topics (perhaps 50 or so). It may work fine to thousands of topics, but you may find some cases are not optimized for thousands of topics and don't work as well as you would hope, and you may need to develop your own fixes and optimizations.
