### ISSUE TITLE
docker build failed on rpi

### ISSUE THREAD

**Issue by daozhu** [nsqio/nsq#1193]
i run command like this:
```shell
docker build ....
```
but failed

>Step 8/14 : RUN ./test.sh
 >---> Running in b07ea5d82ac4
>building apps/nsq_stat
> go: github.com/BurntSushi/toml@v0.3.1: Get https://goproxy.cn/github.com/%21burnt%21sushi/toml/@v/v0.3.1.mod: proxyconnect tcp: net/http: TLS handshake timeout

what is the "%21" means ?

**Comment by ploxiln** [comment]
`%21` is a url-encoded '!' char (see `man ascii` and look under Hex). But this is not the problem. It looks like you are using go 1.13 which is the first version to use a proxy service by default: https://blog.golang.com/module-mirror-launch and it seems that you could not connect to the proxy service due to a temporary outage or a firewall.

**Comment by daozhu** [comment]
yes , i change the go version from latest to 1.12 . and it works well , thanks
