### ISSUE TITLE
nsqadmin -- lookup

### ISSUE THREAD

**Issue by HuangXiaoAIZhu** [nsqio/nsq#1228]
![图片](https://user-images.githubusercontent.com/41467027/71457313-3d1dbe00-27d8-11ea-96ef-c6f2ce7b9bff.png)
![图片](https://user-images.githubusercontent.com/41467027/71457319-4c047080-27d8-11ea-8df1-1b6352c38c11.png)

Is this a bug
Users cannot create topic through nsqadmin
The topic created cannot be implemented to nsqd

**Comment by ploxiln** [comment]
It looks like you are on the `/lookup` page of nsqadmin.

I don't think there is a bug. I think that your nsqd do not have an an appropriate `--broadcast-address` such that nsqadmin (or possibly nsqlookupd) can reach them at that broadcast-address and http port (default 4151).

**Comment by ploxiln** [comment]
(it may help to look at the nsqadmin service logs)

**Comment by HuangXiaoAIZhu** [comment]
What's the requirement of nsqd -- broadcast address? I'm binding the IP address
this is log 
![图片](https://user-images.githubusercontent.com/41467027/71512301-7c2f3a80-28d0-11ea-9a88-d043d79e0f73.png)


This is the script I started
![图片](https://user-images.githubusercontent.com/41467027/71512357-bbf62200-28d0-11ea-827f-d1f8e8a40efd.png)

**Comment by ploxiln** [comment]
The broadcast-address needs to be the address that consumers and nsqadmin can reach nsqd at.

So you're running these things all on one system, and giving the external address ... it's possible that due to your system's firewall (windows or macOS firewall, or ec2 security groups, or ...) they can't make requests to those ports on the external address. For this particular test setup, it might actually work to use 127.0.0.1 for all ip addresses.

... anyway, I assume you either figured this out, or gave up, long ago.
