### ISSUE TITLE
Uneven  distribution on nsqd servers

### ISSUE THREAD

**Issue by dilwaria** [nsqio/nsq#1240]
The scenario is we have consul service discovery before our 2 nsqd servers.  Many times, I can see uneven distribution on the topic depth on both the nsqd. On many topics we depth size as 150k and 70k , gap is of twice. Our cosumers are running as 4,4 on 2 servers with consuming same number of messages from both the nsqd.
Is my publisher uneven?
 Why is it happening ?
My current nsqd setting : 
 

`-max-deflate-level=6 -https-address=0.0.0.0:4152 -broadcast-address=172.21.50.204 -http-address=0.0.0.0:4151 -max-heartbeat-interval=60s -max-body-size=5242880 -data-path=/data -max-msg-size=1048576 -deflate=True -tcp-address=0.0.0.0:4150 -msg-timeout=60s -max-rdy-count=2500 -max-req-timeout=12h0m0s -max-bytes-per-file=104857600 -max-output-buffer-timeout=1s -max-msg-timeout=300s -mem-queue-size=0 -node-id=255 -max-output-buffer-size=65536`

We are persisting every message on the disk. 
@ploxiln @mreiferson  Please help

**Comment by ploxiln** [comment]
If you setup statsd (or statsdaemon), graphite-carbon, graphite-web, and nsqadmin, you can see the rates at which messages are published to the topic on each nsqd:

<img width="1100" alt="Screen Shot 2020-03-11 at 12 17 54 PM" src="https://user-images.githubusercontent.com/649835/76440044-a9e63480-6393-11ea-9b47-70bf7a1e43b5.png">

A simpler way is to restart both nsqd at the same time, then just look at the message totals in the stats of each nsqd:

```
$ curl "http://localhost:4151/stats?topic=events"
nsqd v1.2.0 (built w/go1.10.8)
start_time 2020-01-23T03:50:18Z
uptime 1164h46m55.275999833s
...

Topics:
   [events         ] depth: 0     be-depth: 0     msgs: 12720364 e2e%: 
      [nsq_to_file              ] depth: 0     be-depth: 0     inflt: 26   def: 0    re-q: 0     timeout: 0     msgs: 12720364 e2e%: 
        [V2 archive04            ] state: 3 inflt: 26   rdy: 36   fin: 12720338 re-q: 0        msgs: 12720364 connected: 1164h46m51s

Producers:
   [V2 web24                ] msgs: 1686660  connected: 140h40m5s
      [events         ] msgs: 1686660 
```

Look specifically at "msgs: 12720364".

> Our cosumers are running as 4,4 on 2 servers

I'm not sure what that means. What is the max-in-flight of each consumer? Setting the max-in-flight to be a multiple of the number of nsqd which have the topic may help, if it is not already so.

The nsq system does not have an automatic adjustment for this case. I suppose we haven't cared too much about this particular issue in the past. Most queues are usually near empty, and when they backup and recover over a few hours or so, we haven't cared too much if one nsqd queue emptied faster than another. But in cases where you do care, you can pause the channel on an nsqd so that consumers will focus their work on the other ones.

**Comment by dilwaria** [comment]
We have 2 servers for consumers with 2 clients each, and numofconsumers we set between 200 to 1000 depending on the rate of incoming messages. we have avg of 60k per second incoming messages. 
max-in-flight of each consumer is 2500 the max default limit. 

> A simpler way is to restart both nsqd at the same time, then just look at the message totals in the stats of each nsqd:

I checked this we have a ratio of 3:2  messages of 2 servers

**Comment by ploxiln** [comment]
Then yes, more messages are being produced faster on one of your servers. While both have some queue backup, your consumers are consuming roughly equally from both, leaving much more queue backup on the one producing faster.

We don't have any good way to deal with this situation. If it becomes a real problem, you can pause the channel on the server with the shorter queue, just until the queues are roughly equal again.

**Comment by dilwaria** [comment]
![Screenshot 2020-03-12 at 10 25 11 AM](https://user-images.githubusercontent.com/1715785/76489063-605a2000-644d-11ea-964b-5ed482ffc85c.png)

![Screenshot 2020-03-12 at 10 24 54 AM](https://user-images.githubusercontent.com/1715785/76489114-7536b380-644d-11ea-9f32-f28f557e6586.png)
See these are my current nsqd at 159 and 204 and see the message count difference . As i am persisting all the data to disk, i noticed a spike here on 204 server
![Screenshot 2020-03-12 at 10 41 09 AM](https://user-images.githubusercontent.com/1715785/76489339-1291e780-644e-11ea-88eb-f68ca73386aa.png)

Shall i try with some mem-size-queue to 2500 as in flight

**Comment by ploxiln** [comment]
Sure, or try the default 10,000 mem-queue-size to see how it goes. Usually I accept that if nsqd crashes, some messages will be lost, and minimize this by running `nsq_to_file` on another server (and ensuring it is always keeping-up).
