### ISSUE TITLE
why broadcast-address default value is hostname not ip

### ISSUE THREAD

**Issue by barnettZQG** [nsqio/nsq#1245]
in my case, deploy nsq to kubernetes, hostname cannot be accessed by other services, but register IP  it's no problem. 

I can redo the docker image to solve this problem by getting the IP address and assigning the broadcast-address parameter before starting NSQD.

**Comment by ploxiln** [comment]
If you need to use ip addresses, you should specify the `--broadcast-address={{ip_addr}}` along with the rest of the command-line flags, or in the config file, generated by your deploy/cluster system.

The default is the hostname because the hostname should generally work for reaching the server. It might even have different "internal" and "external" addresses that resolve differently depending on where the consumer is, but always works for that consumer. It was designed in a more server-centric time, when you would typically run one instance of nsqd on each server.

**Comment by barnettZQG** [comment]
docker-entrypoints.sh
```
#!/bin/sh

if [ "$1" = "sh" ];then
    sh
else
    exec /nsqd --lookupd-tcp-address=127.0.0.1:4160 --broadcast-address="${POD_IP}"
fi
```

**Comment by mreiferson** [comment]
ping #1073
