### ISSUE TITLE
nsqd consumer health check mechanism

### ISSUE THREAD

**Issue by iarief** [nsqio/nsq#1273]
Hi, Is there any documentation regarding how nsqd behave when one or more consumer are behaving erratically 
(lots of timeout, lots of error returned)

Would this result in the consumers getting evicted from the channel, or some thing along those lines?

Basically since i found two cases in my app
1. due to wrong config changes, all of my consumer returns error on all nsq message that it consumes, this causes all the consumer to get tcp broken pipe, and somehow kills itself without even trying to reconnect.
2. unbeknownst to me, some channel has a consumer that process a message that require more time than the set msg_timeout config. this also causes the consumer to get disconnected with a broken pipe error but this one actually were able to auto reconnect back to the producer.

nsqd version : 1.1.0
nsq library : github.com/nsqio/go-nsq v1.0.7

**Comment by ploxiln** [comment]
nsqd times-out messages after a configured time period, considers that attempt to  have failed, and re-queues the messages for another delivery/retry.

If you use nsqlookupd for consumers to find nsqd with the topic of interest, then the libraries should do reconnects. I think that `go-nsq` does not do reconnects if you connect directly to nsqd addresses instead of using nsqlookupd addresses. In other cases, you probably want to make sure that your consumer process exits/aborts if nothing is working, and that you use a service manager for the consumer process which will re-start the process from scratch if it exits.

If you look at the nsqd logs, you will see a more precise reason why nsqd decided to disconnect the consumer.
