### ISSUE TITLE
about data files

### ISSUE THREAD

**Issue by cossbow** [nsqio/nsq#1275]
There has some files like *.dat.bad or  *.meta.dat.1345874559747405345.tmp at data dir, how did these files produced? Can i clean them?

**Comment by ploxiln** [comment]
These files are created by the go-diskqueue library, e.g.
https://github.com/nsqio/go-diskqueue/blob/v1.0.0/diskqueue.go#L568
https://github.com/nsqio/go-diskqueue/blob/v1.0.0/diskqueue.go#L462

Any ".bad" files, or ".tmp" files left around, mean that nsqd had an un-clean exit, or disk read/write error. They are left around so that you could theoretically manually recover messages if they are critical and you have sufficient motivation :)

Otherwise, yes, you can delete them.
