### ISSUE TITLE
nsqadmin: graph errors

### ISSUE THREAD

**Issue by Dorsosiv** [nsqio/nsq#1338]
the nsqadmin we have is nsqadmin v1.2.0 (built w/go1.12.9)

the pod was running ok and on chrome the UI looked good: 

## Firefox
![nsq-firefox](https://user-images.githubusercontent.com/76942886/114530148-58257300-9c53-11eb-8a12-4fc87b8c0e09.png)

##Chrome:
![nsq-chrome](https://user-images.githubusercontent.com/76942886/114530337-83a85d80-9c53-11eb-97ad-98572c648926.png)

**Comment by ploxiln** [comment]
The errors are all due to the graph functionality, driven by the `--graphite-url` option. Either it can't reach the running graphite configured, or that graphite doesn't have the stats for these topics/channels/nsqd due to how the nsqd were configured to send stats to graphite.

Note that the browser tries to contact graphite directly, unless you specify `--proxy-graphite`, in which case nsqadmin is what fetches from graphite on behalf of the browser.

Also checkout `--statsd-prefix` configured for both nsqd and nsqadmin, and `--statsd-counter-format` etc options for nsqadmin. This may also depend on the statsd implementation you run.

If you weren't trying to set up graphite, you can just disable it.

**Comment by ploxiln** [comment]
notice that in firefox your graph setting is "2h" and in chrome it's "off"

**Comment by Dorsosiv** [comment]
Thank you
