### ISSUE TITLE
FATAL: --data-path=%s in use (possibly by another instance of nsqd)

### ISSUE THREAD

**Issue by neifeld** [nsqio/nsq#1366]
Hi.
On Linux machine I try to create a new queue with the following command:

**> /home/nsq-linux/nsqd --broadcast-address=10.204.14.197 --tcp-address=0.0.0.0:41510 --http-address=0.0.0.0:41520 --lookupd-tcp-address=0.0.0.0:41610 --max-msg-size=1048576 --max-body-size=10485760 --max-msg-timeout=15m0s --mem-queue-size=10000 --msg-timeout=1m0s --data-path=/home/runtime/data/nsq/nsq_queue_1 --log-level=debug**

When the directory doesn't exist I receive the error:

**> [nsqd] FATAL: --data-path=/home/runtime/data/nsq/nsq_queue_1 in use (possibly by another instance of nsqd)**

If I prepare the directory before this, the command is succeeded.

On Windows machine it works smusly without any preparation and error.

Does anybody have any suggestion how to resolve this issue?
Thank you in advance.
Michael.

**Comment by mreiferson** [comment]
What version of `nsqd` are you running? `nsqd` expects that the `--data-path` directory exists before starting up (although it looks like where it fails we might improve the error message).

**Comment by neifeld** [comment]
We use version 1.1.0.
At Windows it doesn't required that the --data-path directory exists. It makes it on the fly.
The message clearly not describe the situation with the directory existence. 
Please improve the error message.
Thank you.

**Comment by ploxiln** [comment]
With the latest release, v1.2.1, the error now looks like:

> FATAL: failed to instantiate nsqd - failed to lock data-path: open foo/bar: no such file or directory

That could possibly be improved to explicitly check existence or try `os.MkdirAll()`. On windows, the "dirlock" code does literally nothing, there's no multi-instance check implemented for windows, that's why you don't get this error there ... but I'm not sure when/how nsqd creates that directory before writing metadata etc, I can't find where nsqd does that ...
