### ISSUE TITLE
Is this repo project still maintained?

### ISSUE THREAD

**Issue by nitrocode** [nsqio/nsq#1448]
Hi all. Thank you for maintaining this project.

I looked through other issues and didn't see one like this. I see the last release was in Aug 2021. Is this project still maintained?

**Comment by jehiah** [comment]
Yes!  

You are also right that it is time for a release. Thanks for the reminder.  

Generally speaking this project is very stable and battle tested in feature set and operational profile - so we don't often have particular new features to drive releases. I will also say I still personally use NSQ heavily every day at Bitly.

**Comment by nitrocode** [comment]
Hi @jehiah thank you for getting back to me. 

It would be nice to enable dependabot or renovatebot to automate some of the dependencies. I have a client that uses nsq heavily now and has considered moving to kafka solely for the security benefits. Adding a bot to manage dependencies and more frequent releases albeit patch releases, would go along way to keeping nsq alive. Thank you!

**Comment by jvilhuber** [comment]
FWIW companies might start migrating away from NSQ because of perceived pack of maintainance. Not having a release in 2+ years may mean "stable" to some, but looks like neglect to others (particularly to security scanners that scan 1.2.1 and see lots of outdated packages, to say the least).
Is NSQ still serious about this code?
