### ISSUE TITLE
About status of this project

### ISSUE THREAD

**Issue by yai-dev** [nsqio/nsq#1458]
I've noticed that there have been numerous Pull Requests (PRs) offering valuable features, but they seem to have been left unattended for quite some time. I'd like to inquire about the current status of the NSQ project.

**Comment by ploxiln** [comment]
see #1448 

You can see for yourself the status. Development is very slow and sporadic, but there are some companies still using NSQ heavily - perhaps because it's rather easy to modify as needed and make "internal" builds in those companies, and also pretty simple to integrate into larger systems. If NSQ is not responsive to your needs and you feel better off using something else, that's OK.

I've personally not been contributing for about 18 months I guess. Will I find time and motivation to get back into it soon? I don't know :)

**Comment by nitrocode** [comment]
@ploxiln could you pin this issue in case new issues are created? or perhaps create a new issue regarding the maintenance of this project and pin that? This will probably help others who have similar questions.

Thank you again for your support 😄
