### ISSUE TITLE
Having a lot of DISQUEUE errors since upgrading from 1.1.0 to 1.3.0

### ISSUE THREAD

**Issue by GuyCarmy** [nsqio/nsq#1491]
Hi, we have upgraded NSQ from 1.1.0 to 1.3.0 and started having more cases of disk getting full. looks like there are many more .bad files being generated regularly compared to before.
in the logs we see:
```
[nsqd] 2024/06/13 10:26:43.184774 ERROR: DISKQUEUE(topic:channel) reading at 104806550 of /data/topic:channel.diskqueue.000060.dat - EOF
[nsqd] 2024/06/13 10:26:43.184787 WARNING: DISKQUEUE(topic:channel) jump to next file and saving bad file as /data/topic:channel.diskqueue.000060.dat.bad
```
I should add the flags we use while running nsqd:
```
          --max-body-size=10485760 \
          --max-msg-size=10485760 \
          --max-req-timeout=3h0m0s \
          --max-msg-timeout=1h0m0s \
          --lookupd-tcp-address=<address> \
          --data-path=/data \
          --mem-queue-size=0
```

would love any help on how to investigate it. nothing changed other then upgrading from 1.1.0 to 1.3.0.
we are running NSQ on Kubernetes successfully for the past few years.

**Comment by GuyCarmy** [comment]
updating that we have downgraded back to 1.1.0 but we would still love to learn how to debug those errors so we can work with latest version.

**Comment by mreiferson** [comment]
What do you mean more cases of the disk getting full? I would expect files to be marked as bad if the disk is full. Are you suggesting that something changed in NSQ 1.3.0 that resulted in your topics/channels backing up more than they do in 1.1.0?  Without more data it is very difficult to help diagnose.

**Comment by GuyCarmy** [comment]
Hi @mreiferson, i am suggesting that something changed in NSQ 1.3.0 that resulted in more .bad files being created (which leads to the disk getting full, not that the full disk cause the creation of the .bad files...).

i would be happy to share any other data you can suggest to help diagnose it. let me know what you need and can help!

**Comment by GuyCarmy** [comment]
@mreiferson the --mem-queue-size=0 has been like that forever, and is working well with version 1.1.0.

we happen to have "regular" cases where a channel is having a large backlog and the disk is slowly getting full, but in that case its getting full with "real" data, and not with .bad files as happened after upgrading to 1.3.0.

**Comment by TuningYourCode** [comment]
We also discover the issue that since we upgraded to 1.3.0 (docker image) we see many `.bad` files being created. We also run `--mem-queue-size=0` which might be not required for our case as we also run `nsq_to_file` on a seperate maschine.

But as far as i know the `.bad` files should only be created when some kind of error occurs?

Full commandline:
`/nsqd -data-path /data -mem-queue-size 0 -broadcast-address {{ inventory_hostname }} -tcp-address 0.0.0.0:4150 -http-address 0.0.0.0:4151 -lookupd-tcp-address {{ nsq_server_01_host_name }}:4160 -lookupd-tcp-address {{ nsq_server_02_host_name }}:4160 -msg-timeout 10m`

Some numbers:
1680116 messages processed
2 nsqd instances
~9,5GB bad files since 10.01.2025
1 nsq_to_file instance
