### ISSUE TITLE
nsqd: retry health check

### ISSUE THREAD

**Issue by sebest** [nsqio/nsq#594]
Hello,

The disk got full and /ping was reporting it even after the disk usage went down as we resume consuming the channel.

We add to restart the process, otherwise /ping kept reporting NOK

it is with version 0.3.2, so maybe it is fixed now?

thanx

**Comment by mreiferson** [comment]
@sebest is it possible that you hadn't published any additional messages to that channel during that time?

The health is related to the ability to successfully write to disk.  For better or worse, if you never again write to disk it won't currently clear that unhealthy state.

We could force an occasional retry?

**Comment by sebest** [comment]
Got it, as i only write when the status is ok, and if the status is only updated when i write in it, i ended up in a dead lock.
So i guess the only way would be nsq to update its status on a regular basis.

**Comment by mreiferson** [comment]
:+1:

**Comment by mreiferson** [comment]
Now that #671 landed, I'm tempted to close this.

From a client's perspective, it seems like a more reasonable strategy to implement some sort of backoff and retry strategy for a failed `PUB` rather than trying to do something racey like waiting for healthiness after failure and _then_ trying to `PUB` again (i.e. don't check then do something, just try to do it).

What do you think @jehiah (cc @judwhite)?

**Comment by ploxiln** [comment]
I think the client should have to try to PUB and detect failure of that, rather than try to detect health first, because as you say it's race-y to do the latter.

If #625 lands, then you could add a "wait_sync" option to PUB to not return success until the topic's WAL has synced to disk (and nsqd could still batch up a few seconds worth of PUBs before syncing and responding).

Of course, nsqd hasn't bothered with this option thus far because in a typical setup a publisher always PUBs to nsqd running on localhost, and nsqd is pretty darn reliable, and if the server running the publisher and nsqd has some problem then there's not much hope for the publisher anyway. I see now that "filesystem temporarily full" or "filesystem or volume is remote and temporarily unavailable" are actually reasonable cases where the publisher could wait/retry for nsqd to be able to accept the PUB.

**Comment by mreiferson** [comment]
agreed, I'm sold, closing
