### ISSUE TITLE
how to dump protobuf format message from nsq to diskfile with nsq_to_file?

### ISSUE THREAD

**Issue by slvher** [nsqio/nsq#647]
dear,
how to dump protobuf format message from nsq to disk file through the client 'nsq_to_file'?
It seems golang's io package is used inside nsq_to_file and '\n' is the default delimiter between messages.
However, '\n' is also contained in protocol buffer message.
So, how to split protobuf messages rightly in this situation? 

Look forward to your reply. 
Thank you very much.

**Comment by mreiferson** [comment]
hi @slvher, `nsq_to_file` is intended to be a turn-key solution for text-based message formats.  If you're transporting binary formats, you can use `nsq_to_file` as a framework for creating your own consumer.  It could prefix binary blogs with a 4-byte length, for example.

Going to close this since it's more of a question than an issue, but thanks for reaching out!
