### ISSUE TITLE
nsqdlookup for producers?

### ISSUE THREAD

**Issue by ClanStyles** [nsqio/nsq#659]
Why can't you use lookupd for producers too? It seems like specifically choosing a server / dns could create an outage? I have to use SkyDNS to resolve the hostname right now.

**Comment by jehiah** [comment]
`nsqlookupd` has state about where message topics **are**. This means there is a chicken and egg problem with deciding where to put new messages if you have the first message for a topic.

There are a few general paths you can take a) colocate nsqd with whatever is producing messages (ie: always publish to nsqd on the same host), or b) manage your own pool of nsqd's to publish to and use some method to distribute incoming messages to those hosts. c) manage pre-registering the topic topology on the hosts you want to publish to, and use nsqlookupd's for publish discovery (again also defining a method to distribute messages across multiple hosts).

We generally recommend that `nsq` topology be a side effect of your existing topology (ie: option `a`). That also has the advantage of avoiding most types of network failure by keeping the message publish locally instead of involving a remote host, and most often scales seamlessly along with the systems producing messages.

The best overview for general topology choices is here: http://nsq.io/deployment/topology_patterns.html
