### ISSUE TITLE
Deferred messages consumes too much mem and are not durable in deferred status

### ISSUE THREAD

**Issue by chaosue** [nsqio/nsq#674]
__channel stats:__

![shot1](https://cloud.githubusercontent.com/assets/2631612/10689083/3e601b58-79ab-11e5-8000-32fce37c91e4.png)

__channel stats after nsqd restart:__
![shot2](https://cloud.githubusercontent.com/assets/2631612/10689149/9f6b09c6-79ab-11e5-9c17-9a6d29ed66a3.jpg)

__AS we can see above:__
After nsqd restart, all deferred message are no longer deferred , acorddingly they're now in ready status.

__Also:__
With deferred messages , the nsqd consumes os mem up to 29%, if keep increasing the deferred counts, it can uses up the total os mem.

![20151023173452](https://cloud.githubusercontent.com/assets/2631612/10689310/bc489fe4-79ac-11e5-91f6-9216810ee60f.png)

**Comment by mreiferson** [comment]
Hi @chaosue, thanks for your questions.

These are both expected behaviors.  Deferred messages are maintained in memory, at runtime, and flushed to disk when `nsqd` exits.  Upon restart, they are _not_ immediately read and re-defferred.

**Comment by gewentao** [comment]
Hi @mreiferson ,

If nsqd exits at runtime. Upon restart, how to read deferred messages from disk and re-defferred them?

**Comment by ploxiln** [comment]
That would require an interesting feature addition. Currently there is no way for some messages to be automatically deferred as nsqd starts up and reads the disk queues. NSQ consumers will start receiving the messages promptly, and have to re-defer them if that is still needed (or timeout, if that's what caused the deferment initially).

There is a "DPUB" aka deferred-publish endpoint, by popular demand and because it wasn't very difficult or invasive to add. But NSQ was not originally designed to be a "scheduler" so its feature set for that is not thorough. nsqd only really has enough related functionality to enable reasonable "retry" intervals for messages that were intended (perhaps only by a naive system) to be successfully processed immediately, but failed (perhaps naively) unexpectedly.

As a work-around, if it could be determined by looking at the message contents that it should still be deferred, the consumer can re-defer it.
