### ISSUE TITLE
failed ID not in flight

### ISSUE THREAD

**Issue by zhang8h** [nsqio/nsq#729]
`protocol error - E_FIN_FAILED FIN 09e3cdf1b2197000 failed ID not in flight`

`msg 09e3729b4fd97000 attempted 12 times, giving up`

Thing what causes it, the data is lost yet?

- Requeued   : 1,142,034

- Timed Out   : 1,142,019

- Messages   : 20,517,188

**Comment by zhang8h** [comment]
Today there has been such a mistake ： `E_FIN_FAILED FIN 09e4648518997000 failed client does not own message`

**Comment by mreiferson** [comment]
What's causing this are those "timed out" messages - NSQ isn't hearing back from your consumer and it's delivering the message to another consumer.

**Comment by ashitaka1107** [comment]
@mreiferson how to solve this problem?

**Comment by ashitaka1107** [comment]
-msg-timeout="60s": duration to wait before auto-requeing a message
=。=

**Comment by mreiferson** [comment]
@ashitaka1107 your consumer needs to respond to the message before that timeout expires

**Comment by Allan-Nava** [comment]
How can I extend the timeout? @mreiferson

**Comment by ploxiln** [comment]
Your nsq consumer library should have a "msgTimeout" option - e.g. in go-nsq it's in the Config struct: https://godoc.org/github.com/nsqio/go-nsq#Config

That consumer-configured msgTimeout is honored by nsqd only up to nsqd's `--max-msg-timeout` (default 15 minutes).

**Comment by ploxiln** [comment]
Yes, to extend the timeout, you can TOUCH before the timeout, repeatedly, up to the max-msg-timeout

**Comment by ephetic** [comment]
Is there a way for clients to query `nsqd` for the value of `max-msg-timeout`?

**Comment by mreiferson** [comment]
@ephetic it is returned as part of the IDENTIFY response

**Comment by IzaGz** [comment]
got same error- how to fix this?

**Comment by vision9527** [comment]
> Today there has been such a mistake ： `E_FIN_FAILED FIN 09e4648518997000 failed client does not own message`

how to fix this?

**Comment by ploxiln** [comment]
Configure nsqd to give it more time, or process the message faster, or just ignore it.

This isn't necessarily a problem, if it happens rarely - it is a feature that catches the occasional "stuck" consumer. The message will be re-tried (probably by a different consumer, if there are multiple).

If this happens most of the time, then you have to fix something, but it's not one specific thing. Maybe your max-in-flight is way too high, causing messages to wait to be processed for a long while after being delivered. Maybe you just need the consumer to request a few more minutes. Maybe the way you are using nsq just does not work out well, and you need to do something else.

**Comment by vision9527** [comment]
> Configure nsqd to give it more time, or process the message faster, or just ignore it.
> 
> This isn't necessarily a problem, if it happens rarely - it is a feature that catches the occasional "stuck" consumer. The message will be re-tried (probably by a different consumer, if there are multiple).
> 
> If this happens most of the time, then you have to fix something, but it's not one specific thing. Maybe your max-in-flight is way too high, causing messages to wait to be processed for a long while after being delivered. Maybe you just need the consumer to request a few more minutes. Maybe the way you are using nsq just does not work out well, and you need to do something else.

![image](https://user-images.githubusercontent.com/25179277/57517154-c87d3880-7348-11e9-8316-55057731e828.png)
there are not max-msg-timout and msg-timeout in IDENTIFY of consumer received. why?

**Comment by vision9527** [comment]
> Configure nsqd to give it more time, or process the message faster, or just ignore it.
> 
> This isn't necessarily a problem, if it happens rarely - it is a feature that catches the occasional "stuck" consumer. The message will be re-tried (probably by a different consumer, if there are multiple).
> 
> If this happens most of the time, then you have to fix something, but it's not one specific thing. Maybe your max-in-flight is way too high, causing messages to wait to be processed for a long while after being delivered. Maybe you just need the consumer to request a few more minutes. Maybe the way you are using nsq just does not work out well, and you need to do something else.

do you mean configure high -max-msg-timeout or high -msg-timeout?

**Comment by vision9527** [comment]
> Configure nsqd to give it more time, or process the message faster, or just ignore it.
...
![image](https://user-images.githubusercontent.com/25179277/57517955-894fe700-734a-11e9-9645-6e2e31ef5ff0.png)
Is The max_msg_timeout parameter 15min in this picture? not 15sec?

**Comment by ploxiln** [comment]
> 'max_msg_timeout': 900000, 'msg_timeout': 60000,

`max_msg_timeout` is 15 minutes by default, and in your case. This is the nsqd-side setting of the maximum `msg_timeout` that the reader can request. The default `msg_timeout` is just 1 minute though, and that's what you have. So messages time-out after just 1 minute. The client can request a longer msg_timeout, e.g. 5 minutes - up to `max_msg_timeout`.

It looks like you are using pynsq. You can create your `nsq.Reader` with the kwarg `msg_timeout=300` to get a 5 minute message timout (it uses seconds instead of milliseconds, and is documented under the parent-class constructor https://pynsq.readthedocs.io/en/latest/async_conn.html#nsq.AsyncConn).

**Comment by vision9527** [comment]
> Configure nsqd to give it more time, or process the message faster, or just ignore it.
> ...
should i configure nsq params in producer side or consumer side? which params?

**Comment by ploxiln** [comment]
consumer/reader side, set `msg_timeout`.

nsqd `max_msg_timeout` just limits the `msg_timeout` the consumer can set.

**Comment by vision9527** [comment]
> consumer/reader side, set `msg_timeout`.
> 
> nsqd `max_msg_timeout` just limits the `msg_timeout` the consumer can set.

Max_in_flight is 20 in my reader params when message is large, is appropriate？

**Comment by vision9527** [comment]
![image](https://user-images.githubusercontent.com/25179277/57710325-4cb02280-769f-11e9-9070-2c6144f975b1.png)
Always encounter this error when one message processd for over one minute.

**Comment by ploxiln** [comment]
If processing multiple messages at the same time makes them take longer than processing a single message at a time, then 20 is probably too high. For example, if processing a message uses a lot of cpu time, or if it is synchronous/blocking such that only one message is actually processed at a time (and the others are effectively queued in the reader tcp connection while nsqd is already counting down their timeout). max_in_flight=2 is probably better for your case. (It is also possible that processing multiple messages is not slower than processing a single message - if for each you are mostly making async requests and waiting for async responses, e.g. with tornado AsyncHTTPClient, and doing so for all messages processed concurrently.)

I think the reason you're getting "StreamClosedError" is because your handler is synchronous/blocking and blocks the event loop for too long, causing the "heartbeat" to timeout, and nsqd to disconnect the consumer because of that. There are similar settings `--max-heartbeat-interval` (for nsqd) and `heartbeat_interval` (for the Reader). pynsq is admittedly awkward to use if your message processing is synchronous/blocking and takes more than a few seconds.

For further questions it would be better to ask in the google group forum or on IRC (or some people use the golang slack these days I think ...)

**Comment by vision9527** [comment]
> If processing multiple messages at the same time makes them take longer than processing a single ...
Sorry I found the reason.It is the client pynsq's problem.I don't use it in right way, but I have just one final question.
![image](https://user-images.githubusercontent.com/25179277/57750230-fc26dc80-7713-11e9-8655-b7ef538405e7.png)
How to change the HeartbeatInterval's value in nsqd.It is not working by setting -max-heartbeat-interval in nsqd.

**Comment by Ghilteras** [comment]
Do these two errors happen on delete?
```
failed ID not in flight

failed client does not own message
```
Meaning when the Process is done and the consumer tries to remove the msg from the queue?

**Comment by mreiferson** [comment]
> Meaning when the Process is done and the consumer tries to remove the msg from the queue?

Yes, these errors (for the same message ID) would indicate that the first process that received the message timed out, it was delivered to another process that completed, and then the original process tried to `FIN` the message
