### ISSUE TITLE
Support for draining

### ISSUE THREAD

**Issue by JensRantil** [nsqio/nsq#821]
Scenario: I have an `nsq` daemon that I'd like to decommission. I'd like to stop receiving messages, but would like to drain it.

See also https://groups.google.com/forum/#!searchin/nsq-users/Jens$20Rantil%7Csort:relevance/nsq-users/bRvFylU984M/5BRxLA2eBAAJ.

**Comment by ploxiln** [comment]
The main thing to do is stop publishing to that nsqd (but continue consuming from it), until all depths fall to zero on that nsqd.

You *might* be using nsqlookupd to find nsqd instances to *publish* to - just in case you are, let me mention that is not the most common publishing configuration. One common publishing configuration is to always publish to nsqd on localhost, in which case you need to stop all those publishing processes before stopping nsqd in any case. If you are using nsqlookupd for publishers (rather than just for consumers), you'll need to filter the results to take out the instance you want to decommission. (If you have some other scheme, like a static list of nsqd configured for all publishers and consumers, you could deploy changes to all publishers first, or make it two separate lists...)

**Comment by JensRantil** [comment]
Thanks for a great answer!
