### ISSUE TITLE
Why are map deferredMessages and inFlightMessages necessary?

### ISSUE THREAD

**Issue by sparklxb** [nsqio/nsq#885]
I notice there are TODO marks in [channel.go](https://github.com/nsqio/nsq/blob/master/nsqd/channel.go#L482) and try to make some contribution. But with deeper insight, I get confused why they are necessary. In other word, In what conditions will items in deferredPQ/inFlightPQ be missed or duplicated?

**Comment by mreiferson** [comment]
This is probably out of date as the Go runtime/map implementation has improved significantly since that comment was written.

The comment can _probably_ be safely removed and before we do any performance work should profile the application with the latest version of Go to identify any opportunities.
