### ISSUE TITLE
Status of the project

### ISSUE THREAD

**Issue by shinzui** [nsqio/nsq#893]
I am a big fan of NSQ but I've switched to SNS/SQS when we converted our app to microservices since we didn't want to worry about data loss. I've been anxiously monitoring #510 ever since hoping to be able to switch back since NSQ offers a much better developer experience. 

I'm really curious if people are still heavily using NSQ in production, I've seen companies like segment move away from NSQ recently. The other concerning aspect of the project is that @mreiferson is the main/only code contributor. NSQ has a lot of potentials and I hope to see the project flourish, but I'm wondering what's being done to make that happen. Could you please share the status of the project and any future plans?

**Comment by ploxiln** [comment]
Development has been relatively slow over the past year, but it is not at a stand-still, and @mreiferson is not the only one landing changes. For example, from a few days ago: 1e1720f25e09cbcc3385dd5e0475f4c1b2649f9e ... or a couple weeks ago: 0743177ae570ba5b852ed8226edee6fe8d361e2a

There are still some significant users, including at least Bitly and Buzzfeed.

I don't think there are any major plans for the near future, besides a mostly symbolic 1.0 release.

Things are slow because the main contributors and drivers of NSQ are reasonably satisfied with what it does for them today. There are certainly more popular alternatives to NSQ. I think most of us are OK with that.

**Comment by shinzui** [comment]
@ploxiln Does that mean that I shouldn't expect #510 to be completed, nor #887 to be merged?

**Comment by ploxiln** [comment]
I haven't seen any significant movement recently on #510 or #887 and I don't think there will be any in the near future. "Movement" would need people interested in a particular feature to open their own pull request, and refine it until it can be accepted.

#510 seems to be a prerequisite for adding some features from the fork mentioned in #887, and I think there is a reasonable chance of progress on #510 in the medium-to-long term. But I wouldn't wait for it. If you prefer to use something else, that's OK.

**Comment by shinzui** [comment]
Thanks.

**Comment by mreiferson** [comment]
I'll add my thoughts.

First, thanks for reaching out. The project is far from dead. We still meticulously triage incoming issues and respond to questions across GitHub, Slack, Twitter, and Google Groups. I continue to personally use it in production, as do many others.

What we've tried to do recently is clean up some loose ends and confidently stamp NSQ 1.0 as a stable piece of software with the features and tradeoffs it has now. I believe the lack of activity in _code_ is testament to NSQ's stability and robustness for its originally intended problem space. It's unfortunate that in situations like this the perception is that the project is dead rather than "working well, as intended".

However, in the course of our development and use of NSQ, I (and others) have identified areas of improvement that would make it significantly more useful for certain deployments (e.g. #510, et al). I occasionally noodle on #510, but don't have a clear driving force that motivates me other than my own curiosity. Similarly, I think #887 is an impressive and ambitious undertaking and I will happily devote time towards reviewing and providing feedback for smaller scoped changes, but from my cursory glance at the codebase, I would not feel comfortable simply "rubber stamping" a merge of that fork.

Sustainability is important to me, and while I don't personally have the energy I did 5 years ago when we started this project, I'm always open to actionable feedback as to how we can grow the community on the contribution side.

**Comment by shinzui** [comment]
@mreiferson Thank you for the very sensible answer. I agree that #887 is too big to be merged. It would have been ideal if it was initially started as a series of pull requests instead of a fork. I'm wondering if something could be done to solicit contributions in order to move the project forward, assuming that's something you're interested in. Your answer gives a lot of clarity to the status of the project and it might be helpful to share it with the community.
