### ISSUE TITLE
the accomplish about the defaultID

### ISSUE THREAD

**Issue by halleystar** [nsqio/nsq#923]
**defaultID := int64(crc32.ChecksumIEEE(h.Sum(nil)) % 1024)**

I want to know why the defaultID generate by this method and the result is  0 ~ 1024 so why the type is **int64**

**Comment by ploxiln** [comment]
This is because the nsqd defaultID is used as the nodeID in `nsqd/guid.go`, and is then used as a component (via "bitwise or") of an int64 guid for a message.

defaultID / Options.ID could be a smaller type, but it would not really help anything. There are very few instances of it and it is rarely copied around.

**Comment by halleystar** [comment]
what's  the reason that to use the crc32

**Comment by ploxiln** [comment]
just a cheap pseudo-random hash, so a particular hostname always generates the same number for nodeID

**Comment by ploxiln** [comment]
(but a slightly different hostname, eg nsqhost01 vs nsqhost02, generates a different number for nodeID)

**Comment by halleystar** [comment]
oh! thanks
