### ISSUE TITLE
nsq_tail: Add "peek" flag to not consume messages.

### ISSUE THREAD

**Issue by darsenault** [nsqio/nsq#956]
When using NSQ for Extract/Transform/Load (ETL) workflows it would be insanely useful to have a flag in nsq_tail that would allow messages to be displayed but NOT consumed as a way to quality check in-flight data. That is a way to "peek" at (view) and not destructively tail (consume and remove from the queue) messages. I build a consumer that immediately requeues messages, but I'm not sure that's the right way to go about this. Thank you and thank you for NSQ!

**Comment by jehiah** [comment]
You can view messages for any length of time non-destructively by consuming them on a separate channel. If that separate channel is `...#ephemeral` then the channel will not persist after you disconnect, which is typically what's desired. This covers all use cases except when nsq has a backlog of messages for a particular client/channel, because a new ephemeral channel just gets new messages as expected.

The `nsq_tail` `--channel` argument defaults to this use pattern if it's omitted as an argument. 

```go
*channel = fmt.Sprintf("tail%06d#ephemeral", rand.Int()%999999)
```

Does that cover your use?

**Comment by darsenault** [comment]
Thank you jehiah, I think this does cover the data inspection use case. Just to clarify, so long as `nsq_tail` `--channel` is not the _only_ consumer this works, correct? If `nsq_tail` is the only consumer then it appears to consume (destructively) messages. Thanks for the fast reply.

**Comment by jehiah** [comment]
ALL processes that consume from the same `--channel` share a single pool of messages. If you want a separate (non destructive) copy of messages, use a different channel.

i.e. if you run `nsq_to_file --channel=a` and `nsq_tail --channel=a` they will each get roughly half of the messages. If you want `nsq_tail` to get a separate copy of messages it must use it's own unique channel, i.e. `--channel=b`

**Comment by darsenault** [comment]
Thank you so very much. This meets the use case exactly and solves our problem. Keep up the amazing work on NSQ. It is an amazing project!
