### ISSUE TITLE
NSQ message distribution is uneven across multiple nodes

### ISSUE THREAD

**Issue by djmally** [nsqio/nsq#963]
Hi folks,

We're running four machines each with an nsqd living on the box, each with some workers on the box consuming from the same set of topics/channels. All boxes have the same resources & the same number of workers, so the throughput should be roughly the same across all machines.
 
However, we're seeing drastic differences in disk usage across nodes due to uneven message distribution: on two of our nodes, message count is 5x-6x higher than the other two, and we're consistently hitting 90%+ disk usage on those two machines (and occasionally filling the disk completely), while the other two never go above ~35% utilization. 

Scaling issues aside (since that's not the problem I'm trying to solve here), what would be the reason for this uneven distribution? I would expect all nodes to receive an equal portion of messages. For reference, we're using `go-nsq` v1.0.6 as our client to NSQ.

**Comment by ploxiln** [comment]
We need more description of the setup in order to be of much help.

NSQD and the consumer libraries are in charge of distributing messages from nsqd to the consumers. But it sounds like your issue is the number of messages nsqd receives and queues to disk. This is much more up to your applications than it is up to nsqd and the consumer libraries. But, you could be talking about a case where nsq consumers receive messages, and then publish more messages on another topic on the local nsqd. Thus, more details would help.

The distribution of messages is largely dictated by the consumers max_in_flight and how fast they can finish the messages, in case that helps.

You may wish to ask and discuss further on the mailing list: https://groups.google.com/d/forum/nsq-users
