### ISSUE TITLE
How dose NSQ handle consume message failed?

### ISSUE THREAD

**Issue by lindzh** [nsqio/nsq#974]
If a message consume failed,it will re-queue the message. what if it consume failed for many times?
http://nsq.io/overview/design.html

**Comment by ploxiln** [comment]
The consumer has a `MaxAttempts` (go-nsq) or `max_tries` (pynsq) setting.
https://godoc.org/github.com/nsqio/go-nsq#Config
https://pynsq.readthedocs.io/en/latest/reader.html

**Comment by ploxiln** [comment]
Some detail which are probably more in line with what you were asking: When nsqd delivers a message to a consumer, it includes the number of times it has delivered that message to any consumer, due to retries/timeouts. So the go-nsq and pynsq client libraries look at that number, and if it's already over "MaxAttempts" or "max_tries" it immediately marks the message as "finished" without actually processing it. This is how the system "gives up" on a message which failed to be processed many times.

**Comment by lindzh** [comment]
Thanks .

**Comment by lindzh** [comment]
After reading java sdk and nsqd ,I think i got my idea. Is there any idea about getting messages back as it consume failed more than retry time rather than persist in bussiness?

**Comment by bondhan** [comment]
Hi, what about having DLQ (Dead Letter Queue) topic?
